"""empty message

Revision ID: 17e25e97d8d6
Revises: 
Create Date: 2017-02-07 14:05:40.214488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e25e97d8d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('voted', sa.Boolean(), nullable=False),
    sa.Column('quote', sa.String(length=100), nullable=True),
    sa.Column('fav_history', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superlatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superlative_0', sa.Integer(), nullable=False),
    sa.Column('superlative_1', sa.Integer(), nullable=False),
    sa.Column('superlative_2', sa.Integer(), nullable=False),
    sa.Column('superlative_3', sa.Integer(), nullable=False),
    sa.Column('superlative_4', sa.Integer(), nullable=False),
    sa.Column('superlative_5', sa.Integer(), nullable=False),
    sa.Column('superlative_6', sa.Integer(), nullable=False),
    sa.Column('superlative_7', sa.Integer(), nullable=False),
    sa.Column('superlative_8', sa.Integer(), nullable=False),
    sa.Column('superlative_9', sa.Integer(), nullable=False),
    sa.Column('superlative_10', sa.Integer(), nullable=False),
    sa.Column('superlative_11', sa.Integer(), nullable=False),
    sa.Column('superlative_12', sa.Integer(), nullable=False),
    sa.Column('superlative_13', sa.Integer(), nullable=False),
    sa.Column('superlative_14', sa.Integer(), nullable=False),
    sa.Column('superlative_15', sa.Integer(), nullable=False),
    sa.Column('superlative_16', sa.Integer(), nullable=False),
    sa.Column('superlative_17', sa.Integer(), nullable=False),
    sa.Column('superlative_18', sa.Integer(), nullable=False),
    sa.Column('superlative_19', sa.Integer(), nullable=False),
    sa.Column('superlative_20', sa.Integer(), nullable=False),
    sa.Column('superlative_21', sa.Integer(), nullable=False),
    sa.Column('superlative_22', sa.Integer(), nullable=False),
    sa.Column('superlative_23', sa.Integer(), nullable=False),
    sa.Column('superlative_24', sa.Integer(), nullable=False),
    sa.Column('superlative_25', sa.Integer(), nullable=False),
    sa.Column('superlative_26', sa.Integer(), nullable=False),
    sa.Column('superlative_27', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superlatives')
    op.drop_table('people')
    # ### end Alembic commands ###
