"""empty message

Revision ID: 6feb45210e66
Revises: 17e25e97d8d6
Create Date: 2017-02-16 23:00:24.987743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feb45210e66'
down_revision = '17e25e97d8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superlatives', sa.Column('data', sa.Text(), nullable=False))
    op.drop_column('superlatives', 'superlative_27')
    op.drop_column('superlatives', 'superlative_16')
    op.drop_column('superlatives', 'superlative_21')
    op.drop_column('superlatives', 'superlative_20')
    op.drop_column('superlatives', 'superlative_18')
    op.drop_column('superlatives', 'superlative_11')
    op.drop_column('superlatives', 'superlative_5')
    op.drop_column('superlatives', 'superlative_6')
    op.drop_column('superlatives', 'superlative_26')
    op.drop_column('superlatives', 'superlative_13')
    op.drop_column('superlatives', 'superlative_10')
    op.drop_column('superlatives', 'superlative_9')
    op.drop_column('superlatives', 'superlative_24')
    op.drop_column('superlatives', 'superlative_7')
    op.drop_column('superlatives', 'superlative_15')
    op.drop_column('superlatives', 'superlative_17')
    op.drop_column('superlatives', 'superlative_25')
    op.drop_column('superlatives', 'superlative_19')
    op.drop_column('superlatives', 'superlative_23')
    op.drop_column('superlatives', 'superlative_8')
    op.drop_column('superlatives', 'superlative_12')
    op.drop_column('superlatives', 'superlative_1')
    op.drop_column('superlatives', 'superlative_2')
    op.drop_column('superlatives', 'superlative_14')
    op.drop_column('superlatives', 'superlative_4')
    op.drop_column('superlatives', 'superlative_0')
    op.drop_column('superlatives', 'superlative_22')
    op.drop_column('superlatives', 'superlative_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superlatives', sa.Column('superlative_3', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_22', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_0', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_4', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_14', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_2', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_1', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_12', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_8', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_23', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_19', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_25', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_17', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_15', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_7', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_24', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_9', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_10', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_13', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_26', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_6', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_5', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_11', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_18', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_20', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_21', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_16', sa.INTEGER(), nullable=False))
    op.add_column('superlatives', sa.Column('superlative_27', sa.INTEGER(), nullable=False))
    op.drop_column('superlatives', 'data')
    # ### end Alembic commands ###
